### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by daxmc99** [oslabs-beta/Allok8#44]
There doesn't seem to be clear way to use this... Should I just be running `npm install` and `npm run` from the root of the repo?

EDIT: It looks `npm run-script dev` works 🙂 
EDIT 2: `npm run-scrip both` seems to be the way to actually run this repo

**Comment by matti** [comment]
I was about to open an issue about the same topic - confusing

**Comment by rllzrc** [comment]
Hi there! thanks for the feedback, we are currently working on releasing our website later on this week to make it a more seamless process. In the meantime, you're totally right @daxmc99. Thanks again for the time in checking us out/posting this message 🙂🕊

**Comment by rexosariemen** [comment]
Hello @matti  and @daxmc99, if you had clone the repo, you can run it by ‘npm run both’ after doing ‘npm install’ for both dev and production.
